### ISSUE TITLE
Your publishable key is hardcoded into main.js and config.js is ignored

### ISSUE THREAD

**Issue by danzaner** [mixxen/stripe-node-bootstrap#1]
It would really help if you didn't have your own publishable key hardcoded into places like main.js and if you would read the value in config.js instead. Stripe just complains that the tokens are no good if the publishable key and the secret key don't match, but it sure does take a while to figure out what they don't like about your setup.

**Comment by mixxen** [comment]
Your stripe keys should be placed in config.js. The keys in config-example.js need to be replaced with valid keys from https://dashboard.stripe.com/account/apikeys.

config.js is in .gitignore so keys are not accidentally committed to git repo.

**Comment by danzaner** [comment]
What I was trying to say is that your code never uses stripeKeys.publishableKey from config.js. You have a hardcoded call to your own publishable key in main.js: Stripe.setPublishableKey('pk_test_1ejKLCjIWwvKauXLgvNrC7Vx');

That means Stripe charges fail for everyone except you. You use stripeKeys.secretKey in charge.js, but there's no reference to stripeKeys.publishableKey anywhere.

**Comment by mixxen** [comment]
Are you posting this issue to the correct project? I have no file called "main.js" or "charge.js". There are no keys in any of the files.

**Comment by danzaner** [comment]
Sorry about that, mixxen, I had two projects open that I cloned to see how to get a Stripe token via a form. Yours and the other one have similar names and I clicked through to the wrong GitHub issues page. Sorry for wasting your time.
